version: "3.9"
services:
  web:
    build: .
    container_name: mojocom_server
    user: root
    ports:
      - "3000:3000"
    depends_on:
      - mojocom_db
    environment:
      MOJO_ENV: development
      DATABASE_URL: mysql://mojocom:mojocom@db:3306/mojocom_development
    entrypoint: ["bash", "-c", "/opt/MojoCom/script/entrypoint.sh" ]
    command: ["bash", "-c", "/usr/local/bin/morbo /opt/MojoCom/script/mojo_com" ]

  mojocom_db:
    image: mysql:latest
    container_name: mojocom_mysql
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mojocom_development
      MYSQL_USER: mojocom
      MYSQL_PASSWORD: mojocom
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data: