version: "3.9"
services:
  web:
    build: .
    container_name: mojocom_server
    user: root
    ports:
      - "3000:3000"
      - "3001:3001"
      - "5000:5000"
#    depends_on:
#      - mojocom_db
    volumes:
      - /Users/ashutosh/Projects/mojo_com/:/opt/MojoCom/:consistent
      - /Users/ashutosh/Projects/mojo_com/app/:/opt/MojoCom/app/:consistent
      - /tmp/:/tmp/
    environment:
      MOJO_ENV: development
#      DATABASE_URL: mysql://mojocom:mojocom@db:3306/mojocom_development
    entrypoint: "/opt/MojoCom/script/entrypoint.sh"

#  mojocom_db:
#    image: mysql:latest
#    container_name: mojocom_mysql
#    volumes:
#      - "./.mysql-data/db:/var/lib/mysql"
#    restart: always
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_DATABASE: mojocom_development
#      MYSQL_USER: mojocom
#      MYSQL_PASSWORD: mojocom
#      MYSQL_ROOT_PASSWORD: root

#volumes:
#  db_data: